version: '3.11'

services:
  parser:
    container_name: markerplace_parser
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      /bin/bash -c "/parser/docker_scripts/migration_upgrade.sh &&
                     /parser/docker_scripts/start_parsing.sh"
    depends_on:
      - db


  db:
    image: postgres:16
    container_name: markerplace_db
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5438:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: