"""empty message

Revision ID: 64091a4b8606
Revises: 
Create Date: 2025-08-11 11:35:19.671441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64091a4b8606'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS stats')
    op.create_table('facebook_ads_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_parsing', sa.TIMESTAMP(), nullable=False),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('spending', sa.DECIMAL(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='stats'
    )
    op.create_table('tiktok_ads_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_parsing', sa.TIMESTAMP(), nullable=False),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('spending', sa.DECIMAL(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='stats'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiktok_ads_stats', schema='stats')
    op.drop_table('facebook_ads_stats', schema='stats')
    # ### end Alembic commands ###
